name: Caller Workflow First repo
on:

  push:
jobs:
  call-reusable:

    uses: Organization15/central_repo1/.github/workflows/reusable.yaml@main

    with:

      app-name: "my-app1"

    secrets: inherit
